version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:starter
    container_name: streampay-ecommerce-platform
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://uvmpphpocajcdx:a387783ee0f0b866c985580787e529dcbd062e3ab9c5d797cceaa5491441448e@ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/d9kdot9imlgfua/streampay-ecommerce-backend-docker
      REDIS_URL: redis://default:a4onM8LerOvcgMPClLGyQu6hWnZPIS1Oo8Gw0GFptGSHbSweamj1t4PcgwKGHHnu@im2udm.stackhero-network.com:6379
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app/streampay
      - node_modules:/app/medusa/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    expose:
      - 6379

volumes:
  node_modules:
